import type { Case } from "./types";

export const MOCK_CASES: Case[] = [
  {
    case_id: 1,
    creator: "0xA1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
    respondent: "0xB2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3",
    case_title: "Website Redesign — Partial Delivery",
    case_type: "freelance_delivery",
    agreement_summary: "Full website redesign including responsive pages, handoff documentation, and CMS integration for 3,200 GEN.",
    claimant_position: "I delivered the core design system, homepage, and 4 of 7 agreed pages. The client changed requirements mid-project.",
    respondent_position: "Only 4 pages were delivered. The responsive build and CMS integration are completely missing.",
    requested_outcome: "Full payment of 3,200 GEN for substantial completion",
    counter_outcome: "Refund of 2,000 GEN for undelivered work",
    amount_at_stake: 3200,
    asset_symbol: "GEN",
    created_at: "2026-06-20T10:00:00Z",
    evidence_deadline: "2026-07-10T23:59:59Z",
    resolution_deadline: "2026-07-20T23:59:59Z",
    status: "ready_for_resolution",
    evidence: [
      {
        evidence_id: 1,
        case_id: 1,
        submitted_by: "0xA1b2...",
        side: "claimant",
        evidence_type: "work_output",
        title: "Figma Design File — All Screens",
        summary: "Complete design file showing all agreed screens, responsive variants for 4 pages, and the design system.",
        url: "https://figma.com/file/...",
        content_hash: "0xabc123",
        weight_hint: "Proves substantial delivery of agreed design work",
        submitted_at: "2026-06-25T14:00:00Z",
      },
      {
        evidence_id: 2,
        case_id: 1,
        submitted_by: "0xA1b2...",
        side: "claimant",
        evidence_type: "message_thread",
        title: "Slack Thread — Scope Change",
        summary: "Client requested 2 additional page types not in original agreement during week 3.",
        weight_hint: "Shows scope was expanded without additional payment agreement",
        submitted_at: "2026-06-26T09:00:00Z",
      },
      {
        evidence_id: 3,
        case_id: 1,
        submitted_by: "0xB2c3...",
        side: "respondent",
        evidence_type: "agreement",
        title: "Original Contract PDF",
        summary: "Signed agreement lists 7 pages, full responsive, CMS handoff, and documentation as deliverables.",
        url: "https://docs.example.com/contract",
        weight_hint: "Defines what was agreed and what remains incomplete",
        submitted_at: "2026-06-27T11:00:00Z",
      },
    ],
    final_result: {
      outcome_type: "partial_credit",
      claimant_share_bps: 6500,
      respondent_share_bps: 3500,
      claimant_responsibility_bps: 3000,
      respondent_responsibility_bps: 7000,
      confidence_bps: 8100,
      evidence_strength: "strong",
      middle_reason: "Core design work was delivered and the design system is complete. However, responsive pages and CMS integration were not delivered per the signed agreement. Scope change was not formally renegotiated.",
      conditions: ["Claimant must deliver missing responsive pages before any further release.", "Documentation must be provided within 14 days."],
      uncertainties: ["Extent of verbal scope change agreement is unclear."],
      settlement_instruction: "Release 65% (2,080 GEN) to claimant and return 35% (1,120 GEN) to respondent.",
    },
  },
  {
    case_id: 2,
    creator: "0xC3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4",
    respondent: "0xD4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5",
    case_title: "DAO Grant Milestone 2 — Protocol Delay",
    case_type: "grant_milestone",
    agreement_summary: "Technical milestone delivery including working testnet deployment, documentation, and public demo by June 30.",
    claimant_position: "Smart contracts are deployed and tested. Documentation is in progress. Demo was delayed due to infrastructure issues outside our control.",
    respondent_position: "Milestone deadline was missed. Documentation is incomplete and no demo was provided.",
    requested_outcome: "Full milestone payout of 10,000 GEN",
    counter_outcome: "Hold entire milestone pending completion",
    amount_at_stake: 10000,
    asset_symbol: "GEN",
    created_at: "2026-07-01T08:00:00Z",
    evidence_deadline: "2026-07-15T23:59:59Z",
    resolution_deadline: "2026-07-25T23:59:59Z",
    status: "evidence_open",
    evidence: [
      {
        evidence_id: 4,
        case_id: 2,
        submitted_by: "0xC3d4...",
        side: "claimant",
        evidence_type: "public_url",
        title: "Testnet Deployment Link",
        summary: "Live testnet contract deployment showing working protocol.",
        url: "https://testnet.genlayer.io/...",
        weight_hint: "Proves core technical milestone was met",
        submitted_at: "2026-07-03T10:00:00Z",
      },
    ],
  },
  {
    case_id: 3,
    creator: "0xE5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6",
    respondent: "0xF6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1",
    case_title: "Community Forum Conflict",
    case_type: "community_conflict",
    agreement_summary: "Both members agreed to community guidelines including no public accusations without evidence.",
    claimant_position: "Respondent made unfounded public accusations against my character in the governance forum, damaging my reputation.",
    respondent_position: "The accusations were based on visible on-chain behaviour. I have concerns about protocol manipulation.",
    requested_outcome: "Public retraction and 60-day moderation",
    counter_outcome: "No action needed, statements were factual",
    amount_at_stake: 0,
    asset_symbol: "GEN",
    created_at: "2026-06-28T15:00:00Z",
    evidence_deadline: "2026-07-12T23:59:59Z",
    resolution_deadline: "2026-07-22T23:59:59Z",
    status: "responded",
  },
  {
    case_id: 4,
    creator: "0xA7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6",
    respondent: "0xB8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7",
    case_title: "Token Vesting Dispute — Early Exit",
    case_type: "shared_fault_claim",
    agreement_summary: "Contributor vesting schedule with 12-month cliff and early exit penalty clause.",
    claimant_position: "I left due to protocol governance changes that fundamentally altered the project I joined.",
    respondent_position: "The exit is valid but penalty clause applies regardless of reason.",
    requested_outcome: "Waiver of early exit penalty — 4,500 GEN",
    counter_outcome: "Apply penalty clause as written",
    amount_at_stake: 4500,
    asset_symbol: "GEN",
    created_at: "2026-06-15T12:00:00Z",
    evidence_deadline: "2026-07-05T23:59:59Z",
    resolution_deadline: "2026-07-15T23:59:59Z",
    status: "resolved",
    final_result: {
      outcome_type: "shared_fault",
      claimant_share_bps: 5500,
      respondent_share_bps: 4500,
      claimant_responsibility_bps: 4000,
      respondent_responsibility_bps: 6000,
      confidence_bps: 7200,
      evidence_strength: "moderate",
      middle_reason: "Protocol governance changes were material and documented. However, early exit penalty clauses are contractual obligations. A reduced penalty reflects the changed circumstances without fully excusing the exit.",
      conditions: [],
      uncertainties: ["Whether the governance changes constitute a material breach is subject to interpretation."],
      settlement_instruction: "Apply 55% of funds to claimant and 45% penalty deduction. Record shared fault.",
    },
  },
];

export const CASE_TYPE_LABELS: Record<string, string> = {
  freelance_delivery: "Freelance Delivery",
  dao_compensation: "DAO Compensation",
  grant_milestone: "Grant Milestone",
  community_conflict: "Community Conflict",
  shared_fault_claim: "Shared Fault",
  conditional_approval: "Conditional Approval",
  custom: "Custom",
};

export const STATUS_LABELS: Record<string, string> = {
  draft: "Draft",
  open: "Open",
  responded: "Responded",
  evidence_open: "Evidence Open",
  ready_for_resolution: "Ready",
  resolving: "Resolving",
  resolved: "Resolved",
  settled: "Settled",
  cancelled: "Cancelled",
};

export const OUTCOME_LABELS: Record<string, string> = {
  full_claimant_win: "Full Claimant Win",
  full_respondent_win: "Full Respondent Win",
  split_payout: "Split Payout",
  partial_credit: "Partial Credit",
  shared_fault: "Shared Fault",
  conditional_approval: "Conditional Approval",
  staged_release: "Staged Release",
  revision_required: "Revision Required",
  mutual_concession: "Mutual Concession",
  insufficient_evidence: "Insufficient Evidence",
  bad_faith_claim: "Bad Faith Claim",
  manual_review: "Manual Review",
};
